backend:
  name: github
  repo: Malaminzaure/ramli-app-and-books
  branch: main
  base_url: https://decap-cms-oauth-gateway.onrender.com
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Darussan Wa'azi"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Suna (Title)", name: "title", widget: "string"}
      - {label: "Kwanan Wata", name: "date", widget: "datetime"}
      - {label: "Rubutun Darasi", name: "body", widget: "markdown"}
